#!/usr/bin/env bash
# Configure web-02 to be identical to web-01.
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02).
sudo -i
apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
var=$(hostname)
printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    add_header X-Served-By "$var";

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

service nginx start
