#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# - Configure HAproxy so that it send traffic to web-01 and web-02.
# - Distribute requests using a roundrobin algorithm.
# - Make sure that HAproxy can be managed via an init script.
# - Install the latest HAProxy package: https://intranet.alxswe.com/rltoken/2VRAgtKKR9g6Xfb0xzGiSg
# shellcheck disable=SC2154
sudo -i
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg{,.original}
printf %s "

listen lb-01
    bind *:80
    mode http
    balance roundrobin
    server 181417-web-01 34.202.159.210:80 check
    server 181417-web-02 54.90.4.252:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
