#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# - Configure HAproxy so that it send traffic to web-01 and web-02.
# - Distribute requests using a roundrobin algorithm.
# - Make sure that HAproxy can be managed via an init script.

sudo -i
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get install haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg{,.original}
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 181417-web-01 34.202.159.210:80 check
    server 181417-web-02 54.90.4.252:80 check
" > /etc/haproxy/haproxy.cfg

service haproxy restart
