#!/usr/bin/env bash
# Debugs an Nginx server to begin listening on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart