#!/usr/bin/env bash
# This script parses apache log files in list format.
# Displays the visitors IP along with the HTTP status code
#+ from the Apache log file.

myfile="apache-access.log"
awk '{print $1 , $9}' $myfile
