#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/^user\s.*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei '/^[^#].*listen (\[::\]:)?80/ s/80/8080/' /etc/nginx/sites-enabled/default
su nginx -s /bin/bash -c 'service nginx restart'
